export enum ERROR_CODES {
  // common
  INVALID_REQUEST = 'ERR_INVALID_REQUEST',

  // user
  USER_EXISTS = 'ERR_USER_EXISTS',
  CAPTCHA_EXPIRED = 'ERR_CAPTCHA_EXPIRED',
  CAPTCHA_ERROR = 'ERR_CAPTCHA_ERROR',
  USER_NOT_FOUND = 'ERR_USER_NOT_FOUND',
  INVALID_PASSWORD = 'ERR_INVALID_PASSWORD',
  EMAIL_IS_REQUIRED = 'ERR_EMAIL_IS_REQUIRED'
}
