services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - ${SERVER_PORT:-8000}:8000

  database:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imperial_kitchen

volumes:
  mysql_data:
