services:
  database:
    ports:
      - 3306:3306
    volumes:
      - prod_mysql_data:/var/lib/mysql

  redis:
    ports:
      - 6379:6379
    volumes:
      - prod_redis_data:/data

  server:
    build:
      args:
        NODE_ENV: prod
    environment:
      NODE_ENV: prod

volumes:
  prod_mysql_data:
  prod_redis_data:
