services:
  database:
    image: mysql:latest
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imperial_kitchen
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    command: redis-server --save 60 1 --appendonly yes --loglevel warning --requirepass redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - ${SERVER_PORT:-8000}:8000
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      HTTP_PROXY: http://host.docker.internal:7890
      HTTPS_PROXY: http://host.docker.internal:7890
      NO_PROXY: localhost,127.0.0.1
      ALL_PROXY: socks5://host.docker.internal:7891
    extra_hosts:
      - host.docker.internal:host-gateway
    develop:
      watch:
        - path: ./apps/server/package.json
          action: rebuild
        - path: ./apps/server
          target: /usr/src/app/apps/server
          action: sync
