services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        NODE_ENV: prod
    ports:
      - ${SERVER_PORT:-8000}:8000
    environment:
      NODE_ENV: prod
      HTTP_PROXY: http://host.docker.internal:7890
      HTTPS_PROXY: http://host.docker.internal:7890
      NO_PROXY: localhost,127.0.0.1
      ALL_PROXY: socks5://host.docker.internal:7891
    extra_hosts:
      - host.docker.internal:host-gateway
    develop:
      watch:
        - path: ./apps/server/package.json
          action: rebuild
        - path: ./apps/server
          target: /usr/src/app/apps/server
          action: sync
