services:
  database:
    ports:
      - 3307:3306
    volumes:
      - dev_mysql_data:/var/lib/mysql

  server:
    build:
      args:
        NODE_ENV: dev
    environment:
      NODE_ENV: dev

volumes:
  dev_mysql_data:
