services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    depends_on:
      - database
    ports:
      - ${SERVER_PORT:-8000}:8000
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    develop:
      watch:
        - path: ./apps/server/package.json
          action: rebuild
        - path: ./apps/server
          target: /usr/src/app/apps/server
          action: sync

  database:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imperial_kitchen

volumes:
  mysql_data:
