services:
  database:
    ports:
      - 3307:3306
    volumes:
      - dev_mysql_data:/var/lib/mysql

  redis:
    ports:
      - 6380:6379
    volumes:
      - dev_redis_data:/data

  server:
    build:
      args:
        NODE_ENV: dev
    environment:
      NODE_ENV: dev

volumes:
  dev_mysql_data:
  dev_redis_data:
