openapi: 3.0.0
info:
  title: Imperial Kitchen API
  version: 1.0.0
paths:
  /api/auth/sign-in:
    $ref: './paths/auth.yaml#/sign-in'
  /api/user/register/admin:
    $ref: './paths/user.yaml#/register-admin'
  /api/user/register/member:
    $ref: './paths/user.yaml#/register-member'
  /api/user/register/captcha:
    $ref: './paths/user.yaml#/captcha'
components:
  schemas:
    $ref: './components/schemas.yaml#/components/schemas'
tags:
  - name: Auth
    description: 认证相关接口
  - name: User
    description: 用户相关接口
