name: ESLint

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['master']

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: |
          yarn install

      - name: Run ESLint
        run: npx eslint .
          --config eslint.config.cjs
